version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: posexpress-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/RFID-POS
    networks:
      app-net:
        aliases:
          - api.posexpress.app
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: posexpress-web
    ports:
      - "80:80"
    networks:
      app-net:
        aliases:
          - posexpress.app
    depends_on:
      - backend

networks:
  app-net:
    driver: bridge